plugin: yc_compute
folders: # List inventory hosts from these folders.
  - b1gl68u479gjaltnj7dk
filters:
  #- status == 'RUNNING'
  - labels['type'] == 'k8s'
leading_separator: false
auth_kind: serviceaccountfile
service_account_file: /home/user/infra/secrets/tf-sa-key.json
hostnames:
  - fqdn  # Use FQDN for inventory hostnames.
  # You can also format hostnames with jinja2 expressions like this
  # - "{{labels.machinetype}}"
compose:
  # Set ansible_host to the Public IP address to connect to the host.
  # For Private IP use "network_interfaces[0].primary_v4_address.address".
  ansible_host: network_interfaces[0].primary_v4_address.one_to_one_nat.address
  #ansible_ssh_common_args: '"-J ubuntu@158.160.103.247"'
  #ansible_ssh_common_args: '"-o ProxyCommand=`ssh -W %h:%p -q ubuntu@84.201.159.230`"'
keyed_groups:
  # Place hosts in groups named by folder_id.
  #- key: folder_id
  #  prefix: ''
  #  separator: ''
  # Place hosts in groups named by value of labels['group'].
  - key: labels['label']
#groups:
# Place hosts in 'ssd' group if they have appropriate disk_type label.
#  ssd: labels['disk_type'] == 'ssd'
