apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ui.fullname" . }}
  labels:
    name: ui
    release: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    kubernetes.io/ingress.class: "nginx"
    acme.cert-manager.io/http01-edit-in-place: "true"
    service.beta.kubernetes.io/do-loadbalancer-hostname: "ui.xn--e1adnf2fb.xn--p1ai"
spec:
  tls:
  - hosts:
    - ui.xn--e1adnf2fb.xn--p1ai
    secretName: ui-ingress
  rules:
  - host: ui.xn--e1adnf2fb.xn--p1ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-{{ .Chart.Name }}
            port:
              number: {{ .Values.service.externalPort }}
