---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
  labels:
    app: reddit
    component: post
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reddit
      component: post
  template:
    metadata:
      name: post
      labels:
        app: reddit
        component: post
    spec:
      containers:
      - image: asazanoff/post:latest
        name: post
        env:
        - name: POST_DATABASE_HOST
          value: post_db
        - name: POST_DATABASE
          value: posts
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
