---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "comment.fullname" . }}
  labels:
    app: reddit
    component: mongo
    comment-db: "true"
    release: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.databasePort }}
    protocol: TCP
    targetPort: {{ .Values.databasePort }}
  selector:
    app: reddit
    component: mongo
    comment-db: "true"
    release: {{ .Release.Name }}
