apiVersion: v1
kind: Service
metadata:
  name: {{ template "comment.fullname" . }}
  labels:
    app: reddit
    component: comment
    release: {{ .Release.Name }}
spec:
  selector:
    app: reddit
    component: comment
    release: {{ .Release.Name }}
  ports:
  - port: 9292
    protocol: TCP
    targetPort: 9292
   
